# Generated by Django 4.2.5 on 2023-09-25 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compras',
            new_name='Stock',
        ),
    ]
