# Generated by Django 4.2.5 on 2023-09-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_compras_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
