# Generated by Django 4.2.5 on 2023-09-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compras_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='cantidad',
            field=models.IntegerField(default=1, verbose_name=1),
            preserve_default=False,
        ),
    ]
