# Generated by Django 4.2.5 on 2023-09-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_compras_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
