# Generated by Django 4.2.5 on 2023-10-06 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_compras_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
